name: flutter-test
description: 'Runs test'
runs:
  using: "composite"
  steps:
        run: flutter test
      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: test-logs
          path: log/
      - name: Telegram notification
        if: always()
        uses: cbrgm/telegram-github-action@v1.0.26
        with:
          protect-content: true
          disable-web-page-preview: true
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            Status: ${{ job.status }}
            Author: ${{ github.actor }}
            Repo: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Commit: ${{ github.event.head_commit.message }}