name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/niklaslehnfeld/flutter-essentials-docker:master
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1
      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'oracle'
          java-version: '17'
      - uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
      - run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}
          flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Update dependencies
        run: flutter pub upgrade --major-versions
      - name: Build APK
        run: flutter build apk
      - name: Archive APK
        uses: actions/upload-artifact@v4.4.3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*.apk
