name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/niklaslehnfeld/flutter-essentials-docker:master
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1
      - name: Setup JAVA
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2.16.0
        with:
          cache: true
          channel: 'stable'
      - run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}
          flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Update dependencies
        run: flutter pub upgrade --major-versions
      - name: Build APK
        run: flutter build apk --release
      - uses: ncipollo/release-action@v1.9.0
        with:
         artifacts: "build/app/outputs/apk/release/app-release.apk"
