name: Build
on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/niklaslehnfeld/flutter-essentials-docker:master
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1
      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'oracle'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}
          flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Update dependencies
        run: flutter pub upgrade --major-versions
      - name: Build APK
        run: flutter build apk --release
      - uses: ncipollo/release-action@v1
        with:
         artifacts: "build/app/outputs/flutter-apk/*.apk"
         tag: v1.0.5
