on: [push]
name: Code Push
jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.1
            - name: Set up Flutter
              uses: subosito/flutter-action@v2.16.0
              id: flutter-action
              with:
                cache: true
                channel: stable
                architecture: x64
            - run: |
                git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}
                flutter --version 
            - run: flutter --version
            - name: Install dependencies
              run: flutter pub get
            - name: Update dependencies
              run: flutter pub upgrade --major-versions
            - uses: ./.github/actions/test.yml