# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: Test-Build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.18.0
        id: flutter-action
        with:
          cache: true
          channel: stable
          architecture: x64
      - run: |
         git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}
         flutter --version 
      - run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Update dependencies
        run: flutter pub upgrade
      - name: Run tests
        run: flutter test
      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: test-logs
          path: log
      - name: Publish to Telegram
        if: always()
        uses: cbrgm/telegram-github-action@v1.2.3
        with:
          protect-content: true
          disable-web-page-preview: false
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            Status: ${{ job.status }}
            Author: ${{ github.actor }}
            Workflow: ${{ github.workflow }}
            Commit: ${{ github.event.head_commit.message }}
            Changes: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'oracle'
          java-version: '21'
      - name: Update os packages
        run: |
            sudo apt-get update
      - uses: subosito/flutter-action@v2.18.0
        id: flutter-action
        with:
          cache: true
          channel: stable
      - run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}
          flutter --version
      - name: Install flutter dependencies
        run: flutter pub get
      - name: Update flutter dependencies
        run: flutter pub upgrade
      - name: Build APK
        run: flutter build apk
      - name: Archive APK
        uses: actions/upload-artifact@v4.6.0
        id: artifact-upload-step
        with:
          name: test-apk
          path: build/app/outputs/flutter-apk/*.apk
      - name: Download APK
        uses: actions/download-artifact@v4.1.8
        with:
          path: test-apk
          merge-multiple: true
      - run: ls -R test-apk
      - name: Publish to Telegram
        if: ${{ steps.artifact-upload-step.outputs.artifact-id }}
        uses: cbrgm/telegram-github-action@v1.2.3
        with:
          protect-content: true
          disable-web-page-preview: false
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            Workflow: ${{ github.workflow }}
            Author: ${{ github.actor }}
            DL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}