# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: Test
on: []
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        id: flutter-action
        with:
          cache: true
          channel: stable
          architecture: x64
      - run: |
         git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}
         flutter --version 
      - run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Update dependencies
        run: flutter pub upgrade --major-versions
      - name: Run tests
        run: flutter test
      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: test-logs
          path: log/
      - name: Telegram notification
        if: always()
        uses: cbrgm/telegram-github-action@v1.0.26
        with:
          protect-content: true
          disable-web-page-preview: true
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            Status: ${{ job.status }}
            Author: ${{ github.actor }}
            Repo: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Commit: ${{ github.event.head_commit.message }}
 
